# celery
celery:
    build: .
    env_file:
        - container.env
    command: sh start.sh
    links:
        - redis1
        - redis-master

# celery beats
celery_beats:
    build: .
    env_file:
        - container.env
    command: celery -A server.taskq.tasks.app beat --loglevel=INFO
    links:
        - redis1
        - redis-master

# redis servers
redis-master:
    image: redis
    command: redis-server --port 6388  # for celery
    ports:
        - "7389:6388"

redis1:
    image: redis
    command: redis-server --port 6388  # for celery
    ports:
        - "7388:6388"
